cmake `
  -DCMAKE_CXX_SCAN_FOR_MODULES=OFF `
  -DCMAKE_BUILD_TYPE:STRING=Release `
  -DCMAKE_EXPORT_COMPILE_COMMANDS:BOOL=TRUE `
  -DCMAKE_SYSTEM_NAME:STRING=Windows `
  -DCMAKE_MAKE_PROGRAM:STRING=ninja `
  -DCMAKE_INTERPROCEDURAL_OPTIMIZATION:STRING=ON `
  --no-warn-unused-cli `
  -S "$PSScriptRoot\.." -B "$PSScriptRoot\..\build" -G Ninja